### ISSUE TITLE
Path incorrect: Not working on PHP 8.2+ | Works on PHP 8.1

### ISSUE THREAD

**Issue by anburocky3** [craftsys/msg91-php#13]
> Path incorrect: vendor\craftsys\msg91-php\src./ instead of vendor\craftsys\msg91-php\src/ (dot extra)

Already reported it in this repo: https://github.com/craftsys/msg91-laravel/issues/17

**Comment by anburocky3** [comment]
Update: It is working fine in `PHP 8.1.10`, but not working in `PHP 8.2.24`

![image](https://github.com/user-attachments/assets/9f3c3ae3-8253-490a-b3f7-2995c6b50ba9)

**Comment by sudkumar** [comment]
Thanks for reporting. Will check and update.

**Comment by anburocky3** [comment]
Looking forward to resolve this. Thanks.

**Comment by sudkumar** [comment]
@anburocky3 In your vendor folder of the project, please open `craftsys/msg91-php/src/Config.php` and modify the line [19](https://github.com/craftsys/msg91-php/blob/master/src/Config.php#L19) to remove the `.` before the slash in the config path.

```diff
- $this->items = require($base_config_path ?: __DIR__ . "./../config/msg91.php");
+ $this->items = require($base_config_path ?: __DIR__ . "/../config/msg91.php");
```


See if it fixes the issue. Please test on both `8.1` and `8.2`. If it works, I will update it here with a new version.

![diff](https://github.com/user-attachments/assets/c3a5865c-2987-4c22-a0f9-3edcde0e3d03)

**Comment by anburocky3** [comment]
I tried this earlier and it worked!

Changing this to: 
```php
$this->items = require($base_config_path ?: __DIR__ . "/../config/msg91.php");
```

It Worked! 

if you want, let me know. will make a PR of these changes!

**Comment by anburocky3** [comment]
My Pull request here: https://github.com/craftsys/msg91-php/pull/14
